### ISSUE TITLE
Author, hello, the data you shared has expired, can you share it again, thank you!

### ISSUE THREAD

**Issue by xiaozhangtongx** [mircodemarchi/MLDL-Project#2]
Author, hello, the data you shared has expired, can you share it again, thank you!

**Comment by mircodemarchi** [comment]
Motion sense dataset link updated.
The trajectory clustering is private and I can't share publicly, I hope you understand, I'm sorry.

**Comment by xiaozhangtongx** [comment]
ok， thank you very much
